'use client';
import {useEffect,useRef} from 'react';
type Props={steps:any[];cursor:number;guarded:boolean;playing:boolean};
export default function FlowCanvas({steps,cursor,guarded,playing}:Props){const ref=useRef<HTMLCanvasElement>(null);
useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;let frame=0;let active=true;let width=0,height=0;const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const resize=()=>{const box=canvas.getBoundingClientRect();width=box.width;height=box.height;const d=Math.min(devicePixelRatio,2);canvas.width=width*d;canvas.height=height*d;ctx.setTransform(d,0,0,d,0,0);};const observer=new ResizeObserver(resize);observer.observe(canvas);resize();
const draw=(time:number)=>{if(!active)return;ctx.clearRect(0,0,width,height);const w=width,h=height;const compact=w<600;const startX=w*.13,endX=w*.87;const rows=[h*.25,h*.5,h*.75];
ctx.lineWidth=1;for(let y=0;y<12;y++){ctx.strokeStyle='rgba(171,181,195,.055)';ctx.beginPath();ctx.moveTo(w*.5+(0-w*.5)*(1+y*.23),h*.12+y*h*.084);ctx.lineTo(w*.5+(w-w*.5)*(1+y*.23),h*.12+y*h*.084);ctx.stroke();}for(let x=0;x<14;x++){ctx.strokeStyle='rgba(171,181,195,.045)';ctx.beginPath();ctx.moveTo(w*.5+(x-7)*w*.044,0);ctx.lineTo(w*.5+(x-7)*w*.15,h);ctx.stroke();}
const points=steps.filter((s:any)=>s.type!=='telemetry.heartbeat').map((s:any,i:number,arr:any[])=>{const originalIndex=steps.indexOf(s);return {x:startX+(endX-startX)*(i/Math.max(1,arr.length-1)),y:rows[s.action==='recover'||s.action==='hold'||s.action==='refund'?1:s.type.startsWith('gateway')?2:0],s,index:originalIndex};});
const now=points.filter(p=>p.index<=cursor);ctx.setLineDash([3,7]);rows.forEach((y,i)=>{ctx.strokeStyle='rgba(194,205,219,.16)';ctx.beginPath();ctx.moveTo(startX-25,y);ctx.lineTo(endX+25,y);ctx.stroke();});ctx.setLineDash([]);
const color=guarded?'#b8e99f':'#ff7958';for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];const on=b.index<=cursor;ctx.strokeStyle=on?color:'rgba(153,164,183,.14)';ctx.lineWidth=on?2:1;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.bezierCurveTo((a.x+b.x)/2,a.y,(a.x+b.x)/2,b.y,b.x,b.y);ctx.stroke();if(on&&!reduce){const t=((time/2300+i*.17)%1);const x=(1-t)**3*a.x+3*(1-t)**2*t*((a.x+b.x)/2)+3*(1-t)*t*t*((a.x+b.x)/2)+t**3*b.x;const y=(1-t)**3*a.y+3*(1-t)**2*t*a.y+3*(1-t)*t*t*b.y+t**3*b.y;ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,2.3,0,Math.PI*2);ctx.fill();}}
points.forEach(p=>{const on=p.index<=cursor;const current=p.index===cursor;ctx.fillStyle=on?'#222b38':'#171e2a';ctx.strokeStyle=on?color:'#404653';ctx.lineWidth=current?2:1;ctx.beginPath();ctx.arc(p.x,p.y,current?13:9,0,Math.PI*2);ctx.fill();ctx.stroke();if(on){ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.fill();}if(current){ctx.strokeStyle=guarded?'rgba(184,233,159,.15)':'rgba(255,121,88,.15)';ctx.lineWidth=8;ctx.beginPath();ctx.arc(p.x,p.y,21,0,Math.PI*2);ctx.stroke();}ctx.font=`${compact?12:13}px ui-monospace, monospace`;ctx.textAlign='center';ctx.fillStyle=on?'#e1e4e9':'#707b8e';ctx.fillText(`${p.s.at}s`,p.x,p.y+32);if(!compact){ctx.font='13px Arial, sans-serif';ctx.fillText(p.s.action==='hold'?'Action held':p.s.action==='recover'?'Recovery charged':p.s.action==='refund'?'Refund posted':p.s.type.replace('gateway.','Bank: ').replace('webhook.','Notify: ').replace('checkout.','Checkout: ').replace('consent.','Consent: '),p.x,p.y-23);}});
ctx.textAlign='left';ctx.font='12px ui-monospace, monospace';ctx.fillStyle='#7f8a9e';['EVENTS','AGENT','LEDGER'].forEach((t,i)=>ctx.fillText(t,compact?8:20,rows[i]+4));if(!reduce)frame=requestAnimationFrame(draw);};frame=requestAnimationFrame(draw);return()=>{active=false;cancelAnimationFrame(frame);observer.disconnect();};},[steps,cursor,guarded,playing]);
return <canvas ref={ref} className="flow-canvas" role="img" aria-label="Payment event sequence across events, agent actions and bank ledger. The full accessible event list is below."/>;}
