'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowDown,ArrowDownToLine,ArrowLeft,ArrowRight,ArrowUpRight,Beaker,Check,CheckCheck,ChevronDown,ChevronRight,Clock3,Code2,FileCheck2,FlaskConical,History,Info,Layers3,Loader2,Pause,Play,RotateCcw,Search,ShieldCheck,SlidersHorizontal,Sparkles,Upload,X,Zap} from 'lucide-react';
import FlowCanvas from './components/FlowCanvas';
import {scenario,run,makeEvents,minimize,families,familyNames,checks} from '@/lib/simulator.mjs';
const money=(p:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(p/100);
const short=(p:number)=>p>=10000000?`₹${(p/10000000).toFixed(1)}L`:money(p);
const percent=(p:number)=>`${Math.round(p*100)}%`;
const names:Record<string,string>=familyNames;
function initialCase(){let seed=42017;while(true){const s=scenario(seed,'late_capture');const b=run(s,false);if(b.violations.length)return {baseline:b,guarded:run(s,true),minimal:minimize(s,b.violations[0].code),risk:null};seed++;}}
const sources=[
{label:'Razorpay AI Buildathon',type:'THE BRIEF',url:'https://razorpay.com/buildathon/',text:'Open Track: a real problem, meaningful AI, working execution and evidence of value.'},
{label:'Razorpay webhook behaviour',type:'FAILURE MODEL',url:'https://razorpay.com/docs/webhooks/faqs/',text:'Event delivery can repeat. A payment workflow must recognize repeated event IDs.'},
{label:'Late authorisation',type:'FAILURE MODEL',url:'https://razorpay.com/docs/payments/payments/late-authorisation/handle/',text:'Payment status can change after the initial failure. The merchant view and gateway state can disagree.'},
{label:'Antithesis deterministic testing',type:'PRIOR ART',url:'https://antithesis.com/docs/resources/deterministic_simulation_testing/',text:'Reproducible simulation and fault exploration are established techniques. Reprise applies a narrow version to payment workflows.'},
{label:'Anthropic: agent evaluations',type:'EVALUATION DESIGN',url:'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents',text:'Inspect outcomes and trajectories, use deterministic grading where possible, and make failure evidence useful.'},
{label:'Razorpay Agent Studio',type:'COMPETITIVE CONTEXT',url:'https://razorpay.com/agent-studio/',text:'Recovery and risk agents already exist. Reprise focuses on testing the state changes those agents cause.'},
{label:'Galileo agent evaluation',type:'PRIOR ART',url:'https://galileo.ai/',text:'General agent observability and evaluation are an existing category. Payment-specific replay is our narrower scope.'},
{label:'Sierra τ-bench',type:'PRIOR ART',url:'https://sierra.ai/blog/benchmarking-ai-agents',text:'Tool use, policy adherence and repeatable agent behaviour matter beyond a convincing final answer.'}
];
function download(name:string,value:any){const a=document.createElement('a');const u=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:'application/json'}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export default function Page(){const [tab,setTab]=useState('lab');const [detail,setDetail]=useState<any>(initialCase);const [guarded,setGuarded]=useState(false);const [cursor,setCursor]=useState(999);const [playing,setPlaying]=useState(false);const [seed,setSeed]=useState('42017');const [count,setCount]=useState('180');const [strategy,setStrategy]=useState('guided');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [toast,setToast]=useState('');const [suite,setSuite]=useState<any>(null);const [history,setHistory]=useState<any[]>([]);const [report,setReport]=useState<any>(null);const [filter,setFilter]=useState('all');const [query,setQuery]=useState('');const [showImport,setShowImport]=useState(false);const [importText,setImportText]=useState('');const [minimal,setMinimal]=useState(false);const [inspectBusy,setInspectBusy]=useState(false);const sceneRef=useRef<HTMLElement>(null);const listRef=useRef<HTMLElement>(null);
const result=guarded?detail.guarded:detail.baseline;const steps=minimal&&detail.minimal&&!guarded?detail.minimal.result.steps:result.steps;const index=Math.min(cursor,steps.length-1);const current=steps[index];const ledger=current?.ledger??result.ledger;
async function load(){try{const r=await fetch('/api/workspace');const d:any=await r.json();setHistory(d.history??[]);setReport(d.modelReport);}catch{}}
useEffect(()=>{load();},[]);
useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setCursor(c=>{if(c>=steps.length-1){setPlaying(false);return c;}return c+1;}),900);return()=>clearInterval(timer);},[playing,steps.length]);
useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);}},[toast]);
useEffect(()=>{if(!showImport)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setShowImport(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[showImport]);
async function runSuite(replay?:any){setBusy(true);setError('');try{const response=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seed:replay?.seed??Number(seed),count:replay?.count??Number(count),strategy:replay?.strategy??strategy})});const data:any=await response.json();if(!response.ok)throw new Error(data.error);setSuite(data);setReport(data.modelReport);setTab('lab');setToast(data.persisted?'Run complete. Results saved.':'Run complete. History could not be saved; download the report.');await load();setTimeout(()=>listRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),100);}catch(e:any){setError(e.message??'Unable to run the test suite.');}finally{setBusy(false);}}
async function inspect(s:any){setInspectBusy(true);setError('');try{const res=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'inspect',seed:s.seed,family:s.family})});const d:any=await res.json();if(!res.ok)throw new Error(d.error);setDetail(d);setCursor(999);setPlaying(false);setMinimal(false);setGuarded(false);sceneRef.current?.scrollIntoView({behavior:'smooth',block:'start'});}catch(e:any){setError(e.message);}finally{setInspectBusy(false);}}
function selectFamily(f:string){let s=scenario(Number(seed)||42017,f);const b=run(s,false);setDetail({baseline:b,guarded:run(s,true),minimal:b.violations[0]?minimize(s,b.violations[0].code):null,risk:null});setCursor(999);setMinimal(false);setPlaying(false);}
async function importTrace(){setInspectBusy(true);setError('');try{let trace;try{trace=JSON.parse(importText);}catch{throw new Error('The trace must be valid JSON. Download the example to see the format.');}const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'trace',trace})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setDetail(d);setShowImport(false);setTab('lab');setGuarded(false);setMinimal(false);setCursor(999);setToast('Custom event sequence loaded.');}catch(e:any){setError(e.message);}finally{setInspectBusy(false);}}
const filtered=useMemo(()=>suite?.cases.filter((c:any)=>(filter==='all'||filter==='failed'&&c.failed||filter===c.scenario.family)&&(c.scenario.id.toLowerCase().includes(query.toLowerCase())||names[c.scenario.family].toLowerCase().includes(query.toLowerCase())))??[],[suite,filter,query]);
function exportExample(){const s=scenario(42017,'late_capture');download('reprise-example-trace.json',{amount:s.amount,budget:s.budget,events:makeEvents(s)});}
return <div className="app-shell">
<header className="topbar"><a className="brand" href="/" aria-label="Reprise home"><span className="brand-mark"><RotateCcw size={23} strokeWidth={2.5}/></span>reprise<span className="brand-period">.</span></a><nav aria-label="Main navigation">{[{id:'lab',text:'Test lab',icon:FlaskConical},{id:'history',text:'Run history',icon:History},{id:'model',text:'Model & evidence',icon:Layers3},{id:'research',text:'The research',icon:FileCheck2}].map(t=><button key={t.id} className={tab===t.id?'nav-active':''} onClick={()=>setTab(t.id)}><t.icon size={16}/><span>{t.text}</span></button>)}</nav><div className="top-right"><span className="sandbox-badge"><Beaker size={14}/> SIMULATION</span><button className="icon-button" title="Import a custom trace" aria-label="Import a custom trace" onClick={()=>{setError('');setShowImport(true);}}><Upload size={19}/></button></div></header>
<main>
{tab==='lab'&&<>
<section className="intro"><div><div className="eyebrow"><span className="tiny-rule"/> THE PAYMENT-AGENT WIND TUNNEL</div><h1>Find the failure.<br/><span>Before the customer does.</span></h1><p>Put payment workflows under pressure.<br className="desktop-break"/> Every broken rule gets a replay. Every fix gets a retest.</p></div><form className="run-panel" onSubmit={e=>{e.preventDefault();runSuite();}}><div className="run-panel-label"><span>NEW EXPERIMENT</span><FlaskConical size={17}/></div><div className="run-inputs"><label>Test cases<select value={count} onChange={e=>setCount(e.target.value)}><option value="60">60 cases</option><option value="180">180 cases</option><option value="360">360 cases</option></select></label><label>Replay seed<input value={seed} onChange={e=>setSeed(e.target.value)} type="number" min="1" max="1000000000" required/></label></div><label className="strategy-field">Scenario selection<select value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="guided">Learned search + exploration</option><option value="random">Uniform scenario sampling</option></select></label><button className="primary" disabled={busy} type="submit">{busy?<Loader2 size={18} className="spin"/>:<Play size={17} fill="currentColor"/>}{busy?'Running experiment…':'Run experiment'}<span>↵</span></button></form></section>
{error&&!showImport&&<div className="error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
<section className="replay-section" ref={sceneRef}>
<div className="section-heading"><div><span className="section-number">01</span><h2>The replay room</h2><span className="secondary-label">{detail.baseline.scenario.family==='imported_trace'?'Custom trace':'Seeded example'}</span></div><label className="family-select"><select aria-label="Choose failure scenario" value={detail.baseline.scenario.family==='imported_trace'?'':detail.baseline.scenario.family} onChange={e=>selectFamily(e.target.value)}>{detail.baseline.scenario.family==='imported_trace'&&<option value="">Imported trace</option>}{families.map((f:string)=><option value={f} key={f}>{names[f]}</option>)}</select><ChevronDown size={16}/></label></div>
<div className="replay-card"><div className="replay-toolbar"><div className="case-identity"><span className="case-icon"><Activity size={18}/></span><span>{names[detail.baseline.scenario.family]??'Custom sequence'}<small>{detail.baseline.scenario.id} · {money(detail.baseline.scenario.amount)} / purchase</small></span></div><div className="segmented"><button className={!guarded?'selected':''} onClick={()=>{setGuarded(false);setMinimal(false);setCursor(999);}}>Reference policy</button><button className={guarded?'selected safe':''} onClick={()=>{setGuarded(true);setMinimal(false);setCursor(999);}}><ShieldCheck size={14}/> With safeguards</button></div></div>
<div className="scene-layout"><div className="scene"><div className="scene-top"><span className="scene-caption">VIRTUAL TIME · NO REAL MONEY MOVES</span><span className={current?.violations?.length?'status-light failed':'status-light'}>{current?.violations?.length?'Invariant breached':'No breach observed'}</span></div><FlowCanvas steps={steps} cursor={index} guarded={guarded} playing={playing}/><div className="scene-bottom"><span>READ THE EVENT. CHECK THE LEDGER.</span><span>{String(index+1).padStart(2,'0')} / {String(steps.length).padStart(2,'0')}</span></div></div><aside className="ledger-panel"><div className="eyebrow">BANK LEDGER <span>{current?.at??0}s</span></div><div className="ledger-amount">{money(ledger.captured.A+ledger.captured.B)}</div><span className="ledger-sub">total captured in this test</span><div className="ledger-lines"><div><span>Purchase value</span><strong>{money(detail.baseline.scenario.amount)}</strong></div><div><span>Recovery spend</span><strong>{money(ledger.spent)}</strong></div><div><span>Mandate budget</span><strong>{money(detail.baseline.scenario.budget)}</strong></div><div><span>Total refunded</span><strong>{money(ledger.refunded.A+ledger.refunded.B)}</strong></div></div><div className={`ledger-verdict ${current?.violations?.length?'bad':'good'}`}>{current?.violations?.length?<><Activity size={18}/><span>{checks[current.violations[0] as keyof typeof checks]}<small>This rule has been violated.</small></span></>:<><ShieldCheck size={18}/><span>Ledger checks clear<small>At this point in the replay.</small></span></>}</div></aside></div>
<div className="playback"><button aria-label={playing?'Pause replay':'Play replay'} className="play-button" onClick={()=>{if(index>=steps.length-1)setCursor(0);setPlaying(!playing);}}>{playing?<Pause size={16} fill="currentColor"/>:<Play size={16} fill="currentColor"/>}</button><button className="icon-button" aria-label="Restart replay" onClick={()=>{setCursor(0);setPlaying(false);}}><RotateCcw size={16}/></button><input aria-label="Replay event" type="range" min="0" max={Math.max(0,steps.length-1)} value={index} onChange={e=>{setCursor(Number(e.target.value));setPlaying(false);}}/><span className="time-label">{current?.at??0}s</span><button className="text-button" onClick={()=>download('reprise-replay.json',{scenario:detail.baseline.scenario,baseline:detail.baseline,guarded:detail.guarded,minimal:detail.minimal})}><ArrowDownToLine size={16}/><span>Export replay</span></button></div>
</div>
<div className="replay-details"><article className="event-card"><div className="card-heading"><h3>What happened</h3><span>EVENT TRACE</span></div><ol className="event-list">{steps.map((s:any,i:number)=><li key={`${s.id}-${i}`} className={`${i===index?'current':''} ${i>index?'future':''}`}><button onClick={()=>{setCursor(i);setPlaying(false);}}><span className="event-time">{s.at}s</span><span className={`event-dot ${s.action==='hold'?'hold':s.action==='recover'?'recover':''}`}/><span className="event-copy"><strong>{s.type}</strong><span>{s.reason}</span></span><span className={`action-tag ${s.action}`}>{s.action}</span></button></li>)}</ol></article><article className="insight-card"><div className="card-heading"><h3>{guarded?'The intervention':'The smallest explanation'}</h3>{guarded?<ShieldCheck size={18}/>:<Search size={18}/>}</div>{guarded?<><div className="big-insight green">{result.blocked}<span>actions held</span></div><p>State checks run at the moment of action. A pending payment, repeated event, revoked permission or exhausted balance can stop execution.</p><div className="insight-rule"><CheckCheck size={18}/><span>{result.passed?'All five rules passed in this replay.':'This replay still contains a rule violation.'}<small>Passing these tests is not a proof of production safety.</small></span></div></>:detail.minimal?<><div className="minimize-visual"><span>{detail.minimal.originalCount}<small>events</small></span><ArrowRight size={24}/><span>{detail.minimal.events.length}<small>still fail</small></span></div><p>Remove events. Rerun the policy. Keep the removal only if the same rule still breaks. This is a 1-minimal counterexample, not a claim of the globally shortest trace.</p><button className="outline-button" onClick={()=>{setMinimal(!minimal);setCursor(999);setPlaying(false);}}><Layers3 size={16}/>{minimal?'Show full trace':'Replay reduced trace'}<ArrowUpRight size={16}/></button><small className="insight-foot">{detail.minimal.attempts} deletion tests executed</small></>:<><div className="big-insight green"><Check size={36}/><span>No failure to reduce</span></div><p>The reference policy passes this event sequence. Choose another scenario or run a batch to explore different timings.</p></>}</article></div>
</section>
<section className="suite-section" ref={listRef}><div className="section-heading"><div><span className="section-number">02</span><h2>The experiment</h2></div>{suite&&<button className="text-button" onClick={()=>download(`reprise-run-${suite.seed}.json`,suite)}><ArrowDownToLine size={16}/> Download report</button>}</div>{!suite?<div className="suite-empty"><div className="empty-grid">{Array.from({length:48},(_,i)=><span key={i} style={{opacity:.2+(i%7)/10}}/>)}</div><div><h3>One story is a demo.<br/>A batch is evidence.</h3><p>Run the same cases against the reference policy and its guarded version. Inspect every failure, including the cases that pass.</p><button className="text-button" disabled={busy} onClick={()=>runSuite()}>Run your first experiment <ArrowRight size={16}/></button></div><div className="empty-specs"><span><b>06</b> failure families</span><span><b>05</b> executable rules</span><span><b>01</b> reproducible seed</span></div></div>:<>
<div className="metrics"><div><span>REFERENCE FAILURES</span><strong>{suite.summary.baseline.failed}<small>/{suite.count}</small></strong><em>independent test cases</em></div><div><span>AFTER SAFEGUARDS</span><strong className="green">{suite.summary.guarded.failed}<small>/{suite.count}</small></strong><em>same scenarios, same timings</em></div><div><span>SIMULATED EXPOSURE</span><strong>{short(suite.summary.baseline.exposure)}</strong><em>sum of rule-breach amounts*</em></div><div><span>SEARCH METHOD</span><strong className="metric-word">{suite.strategy==='guided'?'Learned':'Uniform'}</strong><em>{suite.strategy==='guided'?'80% ranked · 20% exploration':'uniformly generated scenarios'}</em></div></div>
<div className="suite-body"><div className="case-browser"><div className="browser-controls"><label className="search-input"><Search size={16}/><input placeholder="Find a case or failure…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search test cases"/></label><select aria-label="Filter test cases" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All cases</option><option value="failed">Failures only</option>{families.map((f:string)=><option value={f} key={f}>{names[f]}</option>)}</select></div><div className="case-mosaic" aria-label="Test case results">{filtered.map((c:any,i:number)=><button disabled={inspectBusy} title={`${c.scenario.id}: ${names[c.scenario.family]} — ${c.failed?'failed':'passed'}`} aria-label={`Inspect ${c.scenario.id}, ${c.failed?'failed':'passed'}`} className={c.failed?'case-tile fail':'case-tile pass'} key={c.scenario.id} onClick={()=>inspect(c.scenario)}>{String(i+1).padStart(2,'0')}</button>)}</div><div className="mosaic-legend"><span><i className="fail"/> Reference failed</span><span><i className="pass"/> Reference passed</span><span>{filtered.length} cases · click to replay</span></div><div className="case-table"><div className="table-head"><span>CASE / FAILURE</span><span>EXPOSURE</span><span>GUARDED</span></div>{filtered.slice(0,12).map((c:any)=><button key={c.scenario.id} onClick={()=>inspect(c.scenario)} disabled={inspectBusy}><span><strong>{names[c.scenario.family]}</strong><small>{c.scenario.id}</small></span><span>{money(c.exposure)}</span><span className={c.guardedPassed?'green':'red'}>{c.guardedPassed?<Check size={16}/>:<X size={16}/>} {c.guardedPassed?'Pass':'Fail'}<ChevronRight size={15}/></span></button>)}{filtered.length===0&&<p className="no-results">No cases match this search.</p>}</div></div><aside className="rule-panel"><div className="card-heading"><h3>Rules, not opinions.</h3><ShieldCheck size={19}/></div><p>The ledger decides pass or fail. An AI judge never approves a money action.</p>{suite.summary.baseline.checks.map((c:any)=><div className="rule-row" key={c.code}><div><span>{c.label}</span><small>{c.code==='progress'?'Checks that safe work still completes':'Checked after every state change'}</small></div><b className={c.failed?'red':'green'}>{c.failed?c.failed:<Check size={18}/>}</b></div>)}<div className="method-note"><Info size={16}/><p>*Exposure describes this test suite, not merchant losses. Rule-breach amounts can overlap. The deliberately flawed reference is not a benchmark of a commercial AI model.</p></div></aside></div></>}
</section>
<section className="bottom-note"><div><span className="section-number">03</span><h2>A test you can explain.</h2></div><p>Deterministic events. Integer money. Inspectable decisions.<br/>The evidence should be as clear as the interface.</p><button className="text-button" onClick={()=>setTab('model')}>Read the model card <ArrowUpRight size={17}/></button></section>
</>}
{tab==='history'&&<section className="subpage"><div className="eyebrow">EXPERIMENT LOG</div><h1>Nothing lost.<br/><span>Everything replayable.</span></h1><p className="subpage-intro">Saved run summaries retain the seed, strategy and batch size. Replay to regenerate the cases with the current simulator version.</p>{error&&<div className="error">{error}</div>}<div className="history-list">{history.length?history.map(r=><article key={r.id}><span className="history-icon"><History size={23}/></span><div><h3>Experiment {r.seed}</h3><p>{new Date(r.created_at).toLocaleString()} · {r.count} cases · {r.strategy}</p></div><span><b>{r.summary.baseline.failed}</b><small>reference failures</small></span><span className="green"><b>{r.summary.guarded.failed}</b><small>guarded failures</small></span><button className="outline-button" disabled={busy} onClick={()=>runSuite(r)}><RotateCcw size={16}/> Replay</button></article>):<div className="plain-empty"><History size={32}/><h3>Your first experiment belongs here.</h3><p>Run a batch from the test lab to save a reproducible result.</p><button className="primary" onClick={()=>setTab('lab')}>Open test lab <ArrowRight size={16}/></button></div>}</div></section>}
{tab==='model'&&<section className="subpage"><div className="eyebrow">MEASURED, NOT DECLARED</div><h1>The model has a job.<br/><span>Find useful tests sooner.</span></h1><p className="subpage-intro">A small random forest ranks candidate scenarios before the simulator executes them. It does not decide whether a payment is safe.</p>{report?<><div className="model-hero"><div><span>HELD-OUT SEARCH BUDGET</span><h2>{report.rankedFailures}<small> / {report.searchBudget}</small></h2><p>failures found by pure model ranking</p></div><div className="comparison-bars"><div><span>Learned ranking</span><div><i style={{width:'100%'}}/></div><b>{report.rankedFailures}</b></div><div><span>Random selection</span><div><i className="muted-bar" style={{width:`${report.randomFailuresMean/report.rankedFailures*100}%`}}/></div><b>{report.randomFailuresMean}</b></div><p>Random result is the mean of 1,000 draws. Its central 95% interval is {report.randomFailuresP025}–{report.randomFailuresP975}. The UI adds 20% exploration; its results differ from this pure-ranking benchmark.</p></div></div><div className="model-grid"><article><h3>Training provenance</h3><dl><div><dt>Training executions</dt><dd>{report.trainingRecords.toLocaleString()}</dd></div><div><dt>Held-out executions</dt><dd>{report.heldOutRecords.toLocaleString()}</dd></div><div><dt>Model</dt><dd>32 trees · depth ≤ 6</dd></div><div><dt>Precision / recall</dt><dd>{percent(report.precision)} / {percent(report.recall)}</dd></div><div><dt>Brier score</dt><dd>{report.brier}</dd></div></dl><p>{report.provenance}</p></article><article><h3>Read this before the numbers.</h3><ul>{report.limitations.map((s:string)=><li key={s}>{s}</li>)}</ul><p><strong>The very high classification scores reflect a simple, deterministic reference policy. They do not demonstrate frontier-model intelligence.</strong></p></article></div><button className="outline-button" onClick={()=>download('reprise-model-card.json',report)}><ArrowDownToLine size={16}/> Download model card</button></>:<div className="plain-empty"><p>Loading the model card…</p><button className="outline-button" onClick={load}>Retry</button></div>}<div className="architecture-strip">{[{n:'01',t:'Generate',p:'Vary timing, repeat counts and permission state.'},{n:'02',t:'Prioritize',p:'Rank 80% of tests; retain 20% exploration.'},{n:'03',t:'Execute',p:'Replay both policies with the same event schedule.'},{n:'04',t:'Explain',p:'Check the ledger and reduce failing sequences.'}].map(s=><article key={s.n}><span>{s.n}</span><h3>{s.t}</h3><p>{s.p}</p></article>)}</div></section>}
{tab==='research'&&<section className="subpage"><div className="eyebrow">WHY THIS EXISTS</div><h1>The agent can sound right.<br/><span>The money can still be wrong.</span></h1><p className="subpage-intro">Reprise is a focused Open Track prototype for the Razorpay AI Buildathon. Its proposed contribution is a compact payment simulator with ledger checks, learned scenario selection and counterexample reduction. It does not claim to invent agent testing.</p><div className="research-callout"><span>THE FIVE-MINUTE PROOF</span><h2>Delay a confirmation.<br/>Watch the duplicate charge.<br/>Reduce it. Guard it. Replay it.</h2><button className="primary" onClick={()=>{setTab('lab');selectFamily('late_capture');}}>Open the experiment <ArrowUpRight size={17}/></button></div><div className="source-grid">{sources.map(s=><a href={s.url} target="_blank" rel="noreferrer" key={s.url}><span>{s.type}<ArrowUpRight size={17}/></span><h3>{s.label}</h3><p>{s.text}</p></a>)}</div><div className="research-limits"><a className="outline-button" href="/reprise-source.zip" download><ArrowDownToLine size={16}/> Download complete source</a><h3 style={{marginTop:24}}>What is and isn’t implemented</h3><p>The product runs a discrete-event simulator and two local reference policies, trains and serves a real scenario-ranking model, reduces failing traces, imports custom event sequences, saves run summaries and exports evidence. The downloadable source includes an async local adapter for your own agent. The hosted UI does not execute uploaded code, process real payments, emulate the full Razorpay API or prove a system safe. No Razorpay credentials are required for this simulation. A real integration and merchant validation are the next evaluation steps.</p></div></section>}
</main><footer><a className="footer-brand" href="/">reprise.</a><span>Built for the moments between request and confirmation.</span><span>SIMULATOR v1.0 <span className="footer-slash">/</span> OPEN TRACK</span></footer>
{toast&&<div className="toast" role="status"><CheckCheck size={18}/>{toast}</div>}
{showImport&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setShowImport(false);}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="import-title"><div className="card-heading"><h2 id="import-title">Bring your own sequence.</h2><button className="icon-button" onClick={()=>setShowImport(false)} aria-label="Close import"><X size={20}/></button></div><p>Paste normalized events to test the included reference policies. Amounts are in paise. Events run in timestamp order.</p><button className="text-button" onClick={exportExample}><ArrowDownToLine size={16}/> Download an example JSON trace</button><label className="upload-label">Load JSON file<input type="file" accept="application/json,.json" onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>200000){setError('Choose a JSON file smaller than 200 KB.');return;}setImportText(await f.text());}}}/></label><textarea autoFocus aria-label="JSON event trace" spellCheck={false} value={importText} onChange={e=>setImportText(e.target.value)} placeholder={'{ "amount": 500000, "budget": 600000, "events": [...] }'}/>{error&&<div className="error" role="alert">{error}</div>}<div className="modal-actions"><button className="outline-button" onClick={()=>setShowImport(false)}>Cancel</button><button className="primary" disabled={inspectBusy||!importText.trim()} onClick={importTrace}>{inspectBusy?<Loader2 className="spin" size={16}/>:<Play size={16}/>} Run trace</button></div></section></div>}
</div>;
}
