import {NextRequest,NextResponse} from 'next/server';
import {z} from 'zod';
import {batch,run,summarize,minimize,scenario,families,makeEvents} from '@/lib/simulator.mjs';
import {score,modelReport} from '@/lib/search';
import {database} from '@/lib/db';
const headers={'Cache-Control':'no-store'};
const input=z.object({seed:z.number().int().min(1).max(1000000000).default(42017),count:z.number().int().min(12).max(360).default(180),strategy:z.enum(['guided','random']).default('guided')});
export async function GET(req:NextRequest){try{const history=await database().prepare('SELECT id, created_at, seed, count, strategy, summary FROM simulation_runs ORDER BY created_at DESC LIMIT 12').all();return NextResponse.json({history:history.results.map((r:any)=>({...r,summary:JSON.parse(r.summary)})),modelReport},{headers});}catch{return NextResponse.json({history:[],modelReport,warning:'Saved runs are temporarily unavailable. You can still run simulations.'},{headers});}}
export async function POST(req:NextRequest){try{if(req.headers.get('origin')&&req.headers.get('origin')!==req.nextUrl.origin)return NextResponse.json({error:'Origin not allowed'},{status:403});const raw=await req.text();if(raw.length>220000)return NextResponse.json({error:"Request exceeds the 220 KB limit"},{status:413});const body=JSON.parse(raw);
if(body.operation==='inspect'){const s=z.object({seed:z.number().int().min(1).max(2000000000),family:z.enum(families as [string,...string[]])}).parse(body);const sc=scenario(s.seed,s.family);const baseline=run(sc,false);return NextResponse.json({baseline,guarded:run(sc,true),minimal:baseline.violations[0]?minimize(sc,baseline.violations[0].code):null,risk:score(sc)},{headers});}
if(body.operation==='trace'){const event=z.object({at:z.number().min(0).max(86400),type:z.enum(['checkout.failed','gateway.captured','gateway.failed','webhook.captured','recovery.request','consent.revoked','refund.request','telemetry.heartbeat']),id:z.string().min(1).max(80),intent:z.enum(['A','B']).default('A'),snapshot:z.number().int().nonnegative().optional()});const parsed=z.object({amount:z.number().int().min(100).max(100000000),budget:z.number().int().min(100).max(200000000),events:z.array(event).min(1).max(200)}).parse(body.trace);const sc={...scenario(1,'clean_control'),amount:parsed.amount,budget:parsed.budget,family:'imported_trace'};const events=parsed.events.slice().sort((a,b)=>a.at-b.at);return NextResponse.json({baseline:run(sc,false,events),guarded:run(sc,true,events),minimal:null,risk:null},{headers});}
const p=input.parse(body);let candidates=batch(p.seed,p.strategy==='guided'?p.count*4:p.count);let selected=candidates;
if(p.strategy==='guided'){const ranked=candidates.map((s:any)=>({s,r:score(s)})).sort((a:any,b:any)=>b.r-a.r);const n=Math.floor(p.count*.8);const top=ranked.slice(0,n).map((r:any)=>r.s);const ids=new Set(top.map((s:any)=>s.id));selected=[...top,...candidates.filter((s:any)=>!ids.has(s.id)).slice(0,p.count-n)];}
const baseline=selected.map((s:any)=>run(s,false)),guarded=selected.map((s:any)=>run(s,true));const summary={baseline:summarize(baseline),guarded:summarize(guarded)};const id=crypto.randomUUID();const createdAt=new Date().toISOString();let persisted=true;try{await database().prepare('INSERT INTO simulation_runs (id, created_at, seed, count, strategy, summary) VALUES (?, ?, ?, ?, ?, ?)').bind(id,createdAt,p.seed,p.count,p.strategy,JSON.stringify(summary)).run();}catch{persisted=false;}
return NextResponse.json({id,createdAt,...p,persisted,summary,cases:baseline.map((r:any,i:number)=>({scenario:r.scenario,failed:!r.passed,violations:r.violations,exposure:r.exposure,risk:score(r.scenario),guardedPassed:guarded[i].passed})),modelReport},{headers});
}catch(e){return NextResponse.json({error:e instanceof z.ZodError?'Invalid request. Check the seed, batch size or trace format.':'The simulation could not finish. Please try again.'},{status:400,headers});}}
